name: Build

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: remove previous app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku apps:destroy $APP_NAME --confirm $APP_NAME
      
      - name: create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku create $APP_NAME
        
      - name: push app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        working-directory: .
        run: heroku container:push web -a $APP_NAME
        
      - name: release app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku container:release web -a $APP_NAME
